version: '2'
services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: bobarniov
      POSTGRES_PASSWORD: kabanos
      POSTGRES_DB: tms_education
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

  nginx:
    build: ./nginx
    ports:
      - 1337:80

  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  migration:
    build: .
    command: python manage.py migrate
